import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavContainer from "./Components/Header/navContainer";
import ClientComponent from "./clientComponent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <head>
        <title>MonBuy</title>
        <link rel="icon" href="./favicon.ico" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}
      >
        <ClientComponent />
        <header>
          <nav>
            <NavContainer />
          </nav>
        </header>
      </body>
    </html>
  );
}
